PATH = "C:\Program Files (x86)\chromedriver.exe"
SERVER_PATH_X2_AMERICA = "https://ts20.x2.america.travian.com/"
SERVER_PATH_X2_ASIA = "https://ts20.x2.asia.travian.com/"
USER_NAME = "GloryToEladR"  # "GloryToelad"
PASSWORD = "bottestv1"

NAVIGATION = "navigation"
BUILDING_SLOT = "buildingSlot"
BUILDING_LIST = "buildingList"
buildingSlot = "buildingSlot{loc}"
WOOD = 'wood'
CLAY = 'clay'
IRON = 'iron'
CROP = 'crop'
RSS = [WOOD, CLAY, IRON, CROP]
RSS_ICON = "resourceView"
BUILDING_ICON = "buildingView"
MAP_ICON = "map"
STATISTICS_ICON = "statistics"
REPORT_ICON = "reports"
MESSAGES_ICON = "messages"
DAILY_QUESTS_ICON ="dailyQuests"
BUTTON = "button"
LOGIN = "Login"
